[package]
name = "rustic_server"
version = "0.1.0"
authors = ["Alexander Weiss <alex@weissfam.de>"]
categories = ["command-line-utilities"]
edition = "2021"
homepage = "https://rustic.cli.rs/"
keywords = ["backup", "restic", "deduplication", "encryption", "cli", "server"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/rustic-rs/rustic_server"
description = """
rustic server - a REST server built in rust to use with rustic and restic.
"""

[dependencies]
anyhow = "1.0.75"
async-std = { version = "1", features = ["attributes"] }
async-trait = "0.1"
axum = "0.6.20"
axum-auth = "0.4.0"
axum-server = { version = "0.5.1", features = ["tls-rustls"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.4.2", features = ["derive"] }
htpasswd-verify = "0.3"
http-range = "0.1"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
walkdir = "2"
