[target.x86_64-pc-windows-gnu]
# additional commands to run prior to building the package
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get --assume-yes install nasm:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH",
]

[target.x86_64-pc-windows-gnu.env]
passthrough = [
  "AWS_LC_SYS_PREBUILT_NASM=1",
]
