[default] # Default repository
alex = "Read" # Alex can read
admin = "Modify" # admin can modify, so has full access, even delete

[alex] # a repository named 'alex'
alex = "Modify" # Alex can modify his own repository
bob = "Append" # Bob can append to Alex's repository
