# Adapt to your own configuration, a full list of options can be found at:
# https://github.com/rustic-rs/rustic/tree/main/config
[global]
log-level = "info"
log-file = "~/rustic.log"

[repository]
repository = "rest:http://rustic:rustic@127.0.0.1:8000/ci_repo"
password = "rustic"

[backup]

[[backup.snapshots]]
sources = ["src"]
