[server]
listen = "127.0.0.1:8000"

[storage]
data-dir = "./test_data/test_repos/"

[auth]
auth-path = "/test_data/test_repo/htaccess"
disable-auth = false

[acl]
acl-path = "/test_data/test_repo/acl.toml"
private-repo = true
append-only = false

[tls]
tls = true
tls-cert = "/test_data/test_repo/cert.pem"
tls-key = "/test_data/test_repo/key.pem"
